steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/palliativecare1642/palliative-care-api:$COMMIT_SHA', '.']
  env:
  - 'DOCKER_BUILDKIT=1'
images:
- 'gcr.io/palliativecare1642/palliative-care-api:$COMMIT_SHA'
