#spring.application.name=PalliativeCare

spring:
  application:
    name: PalliativeCare
  data:
    mongodb:
      uri: mongodb+srv://mawklyzuxz:SEflCIsCeDlY7l0e@cluster0.57qg7zh.mongodb.net/palliativeCareDB?retryWrites=true&w=majority&appName=Cluster0

jwt:
  secret: "ET2VTlBAAT603eAEFzWb1wru9y3vDh+P8bqm1uNE19QL1U9B"
  expiration: 7d
server:
  port: 8080