#spring.application.name=PalliativeCare

spring:
  application:
    name: PalliativeCare
  data:
    mongodb:
      uri: ${MONGO_URI}

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 7d
server:
  port: ${PORT:8080}

cloudinary:
  url: ${CLOUDINARY_CLOUD_URL}


