#spring.application.name=PalliativeCare

spring:
  application:
    name: PalliativeCare
  data:
    mongodb:
      uri: ${MONGO_URI}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  main:
    lazy-initialization: true

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 7d
server:
  port: ${PORT:8080}

cloudinary:
  url: ${CLOUDINARY_CLOUD_URL}


